/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "llpnribaixdccodhxslv";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxscG5yaWJhaXhkY2NvZGh4c2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NTE5MDEsImV4cCI6MjA3NjAyNzkwMX0.HcpHGHdiue1F8A5avK9YKetOo9Rg6rd0DgHFl4JgPMI";
